export const CATEGORIES = (
  [
    ['Colares', 'colares'],
    ['Brincos', 'brincos'],
    ['Anéis', 'aneis'],
    ['Pulseiras', 'pulseiras'],
    ['Conjuntos', 'conjuntos'],
    ['Piercings', 'piercings'],
  ] as const
).map(([nome, slug], i) => ({ nome, slug, imagem: null, ordem: i, ativa: true }));

/**
 * Catálogo de demonstração. `imagens` fica vazio de propósito — a vitrine cai no
 * placeholder até que fotos reais sejam enviadas; basta preencher o array depois.
 */
export interface SeedProduct {
  nome: string;
  slug: string;
  descricao: string;
  cuidados: string;
  preco: number;
  precoPromocional?: number;
  material: 'PRATA_925' | 'BANHADO_OURO';
  categoria: string;
  estoque: number;
  pesoGramas: number;
  pedra?: string;
  tamanhos?: string[];
  destaque?: boolean;
  lancamento?: boolean;
  notaMedia: number;
  totalAvaliacoes: number;
}

const CUIDADO_OURO =
  'Evite contato com perfumes, cloro e produtos de limpeza. Guarde em saquinho individual e seque bem após o uso para preservar o banho.';
const CUIDADO_PRATA =
  'Limpe com flanela seca após o uso. Guarde em local seco e fechado para retardar a oxidação natural da prata.';

export const PRODUCTS: SeedProduct[] = [
  // ─── Colares ───────────────────────────────────────────────────────────────
  {
    nome: 'Colar Ponto de Luz Zircônia',
    slug: 'colar-ponto-de-luz-zirconia',
    descricao:
      'Um clássico que nunca sai de moda. Corrente veneziana delicada com pingente de zircônia lapidada que capta a luz em qualquer ângulo. Perfeito para usar sozinho ou compondo mix de colares.',
    cuidados: CUIDADO_OURO,
    preco: 149.9,
    precoPromocional: 119.9,
    material: 'BANHADO_OURO',
    categoria: 'colares',
    estoque: 34,
    pesoGramas: 3.2,
    pedra: 'Zircônia',
    tamanhos: ['40cm', '45cm'],
    destaque: true,
    notaMedia: 4.8,
    totalAvaliacoes: 47,
  },
  {
    nome: 'Colar Gargantilha Elos Grossos',
    slug: 'colar-gargantilha-elos-grossos',
    descricao:
      'Gargantilha de elos largos com acabamento polido espelhado. Peça statement que transforma o look básico e dialoga bem com decotes abertos.',
    cuidados: CUIDADO_OURO,
    preco: 229.9,
    material: 'BANHADO_OURO',
    categoria: 'colares',
    estoque: 18,
    pesoGramas: 12.4,
    tamanhos: ['38cm', '42cm'],
    destaque: true,
    notaMedia: 4.7,
    totalAvaliacoes: 31,
  },
  {
    nome: 'Colar Corrente Cadeado',
    slug: 'colar-corrente-cadeado',
    descricao:
      'Inspirado nas correntes de cadeado clássicas, com elos ovais alongados. Estrutura firme e fecho reforçado para uso diário.',
    cuidados: CUIDADO_OURO,
    preco: 189.9,
    precoPromocional: 159.9,
    material: 'BANHADO_OURO',
    categoria: 'colares',
    estoque: 7,
    pesoGramas: 9.8,
    tamanhos: ['40cm', '45cm', '50cm'],
    notaMedia: 4.6,
    totalAvaliacoes: 22,
  },
  {
    nome: 'Colar Prata Cordão Baiano',
    slug: 'colar-prata-cordao-baiano',
    descricao:
      'Cordão baiano em prata 925 maciça, trançado à mão. Peso e caimento que só a prata legítima entrega. Unissex.',
    cuidados: CUIDADO_PRATA,
    preco: 279.9,
    material: 'PRATA_925',
    categoria: 'colares',
    estoque: 12,
    pesoGramas: 18.6,
    tamanhos: ['50cm', '60cm', '70cm'],
    notaMedia: 4.9,
    totalAvaliacoes: 38,
  },
  {
    nome: 'Colar Prata Medalha Lisa',
    slug: 'colar-prata-medalha-lisa',
    descricao:
      'Medalha circular lisa em prata 925, ideal para gravação personalizada. Acompanha corrente singapura de 45cm.',
    cuidados: CUIDADO_PRATA,
    preco: 199.9,
    material: 'PRATA_925',
    categoria: 'colares',
    estoque: 25,
    pesoGramas: 7.4,
    tamanhos: ['45cm'],
    lancamento: true,
    notaMedia: 4.5,
    totalAvaliacoes: 14,
  },
  {
    nome: 'Colar Escapulário Pérola',
    slug: 'colar-escapulario-perola',
    descricao:
      'Escapulário longo com pérolas de água doce intercaladas em corrente fina. Comprimento que valoriza sobreposições.',
    cuidados: CUIDADO_OURO,
    preco: 259.9,
    material: 'BANHADO_OURO',
    categoria: 'colares',
    estoque: 15,
    pesoGramas: 11.2,
    pedra: 'Pérola de água doce',
    tamanhos: ['70cm', '80cm'],
    lancamento: true,
    notaMedia: 4.8,
    totalAvaliacoes: 19,
  },

  // ─── Brincos ───────────────────────────────────────────────────────────────
  {
    nome: 'Brinco Argola Média Lisa',
    slug: 'brinco-argola-media-lisa',
    descricao:
      'Argola de 3cm com tubo redondo e acabamento polido. O meio-termo perfeito entre discrição e presença — vai do escritório ao happy hour.',
    cuidados: CUIDADO_OURO,
    preco: 99.9,
    precoPromocional: 79.9,
    material: 'BANHADO_OURO',
    categoria: 'brincos',
    estoque: 52,
    pesoGramas: 2.8,
    destaque: true,
    notaMedia: 4.9,
    totalAvaliacoes: 86,
  },
  {
    nome: 'Brinco Ear Cuff Cravejado',
    slug: 'brinco-ear-cuff-cravejado',
    descricao:
      'Ear cuff de encaixe sem necessidade de furo, cravejado com micro zircônias. Vendido como peça avulsa para composições assimétricas.',
    cuidados: CUIDADO_OURO,
    preco: 89.9,
    material: 'BANHADO_OURO',
    categoria: 'brincos',
    estoque: 41,
    pesoGramas: 1.4,
    pedra: 'Micro zircônia',
    lancamento: true,
    notaMedia: 4.6,
    totalAvaliacoes: 27,
  },
  {
    nome: 'Brinco Gota Cristal',
    slug: 'brinco-gota-cristal',
    descricao:
      'Pendente em formato de gota com cristal lapidado. Movimento leve e brilho intenso — escolha certeira para festas e casamentos.',
    cuidados: CUIDADO_OURO,
    preco: 159.9,
    precoPromocional: 129.9,
    material: 'BANHADO_OURO',
    categoria: 'brincos',
    estoque: 23,
    pesoGramas: 4.6,
    pedra: 'Cristal',
    notaMedia: 4.7,
    totalAvaliacoes: 33,
  },
  {
    nome: 'Brinco Prata Argola Pequena',
    slug: 'brinco-prata-argola-pequena',
    descricao:
      'Argola de 1,2cm em prata 925 maciça com fecho de clique. Tão confortável que dá para dormir com ela. Ideal para segundo furo.',
    cuidados: CUIDADO_PRATA,
    preco: 79.9,
    material: 'PRATA_925',
    categoria: 'brincos',
    estoque: 68,
    pesoGramas: 1.2,
    destaque: true,
    notaMedia: 4.9,
    totalAvaliacoes: 112,
  },
  {
    nome: 'Brinco Prata Estrela Delicada',
    slug: 'brinco-prata-estrela-delicada',
    descricao:
      'Micro estrela em prata 925 com tarraxa de pressão. Discreto, leve e perfeito para uso contínuo.',
    cuidados: CUIDADO_PRATA,
    preco: 69.9,
    material: 'PRATA_925',
    categoria: 'brincos',
    estoque: 5,
    pesoGramas: 0.8,
    notaMedia: 4.8,
    totalAvaliacoes: 41,
  },
  {
    nome: 'Brinco Argola Texturizada Grande',
    slug: 'brinco-argola-texturizada-grande',
    descricao:
      'Argola de 5cm com textura martelada artesanal. Cada peça tem marcações únicas — leveza surpreendente para o tamanho.',
    cuidados: CUIDADO_OURO,
    preco: 139.9,
    material: 'BANHADO_OURO',
    categoria: 'brincos',
    estoque: 19,
    pesoGramas: 3.9,
    lancamento: true,
    notaMedia: 4.5,
    totalAvaliacoes: 16,
  },

  // ─── Anéis ─────────────────────────────────────────────────────────────────
  {
    nome: 'Anel Solitário Zircônia',
    slug: 'anel-solitario-zirconia',
    descricao:
      'Solitário clássico com zircônia central de 6mm em garras altas. A pedra fica elevada, o que amplifica o brilho e facilita a limpeza.',
    cuidados: CUIDADO_OURO,
    preco: 169.9,
    precoPromocional: 139.9,
    material: 'BANHADO_OURO',
    categoria: 'aneis',
    estoque: 29,
    pesoGramas: 2.6,
    pedra: 'Zircônia',
    tamanhos: ['14', '16', '18', '20', '22'],
    destaque: true,
    notaMedia: 4.8,
    totalAvaliacoes: 54,
  },
  {
    nome: 'Anel Aparador Cravejado',
    slug: 'anel-aparador-cravejado',
    descricao:
      'Meia aliança cravejada com zircônias em trilho. Feito para compor com o solitário, mas se sustenta sozinho.',
    cuidados: CUIDADO_OURO,
    preco: 129.9,
    material: 'BANHADO_OURO',
    categoria: 'aneis',
    estoque: 31,
    pesoGramas: 1.9,
    pedra: 'Zircônia',
    tamanhos: ['14', '16', '18', '20'],
    notaMedia: 4.6,
    totalAvaliacoes: 28,
  },
  {
    nome: 'Anel Prata Falange Liso',
    slug: 'anel-prata-falange-liso',
    descricao:
      'Anel de falange fino em prata 925 com acabamento acetinado. Ajustável na base para adaptação ao dedo.',
    cuidados: CUIDADO_PRATA,
    preco: 59.9,
    precoPromocional: 47.9,
    material: 'PRATA_925',
    categoria: 'aneis',
    estoque: 74,
    pesoGramas: 0.9,
    tamanhos: ['Ajustável'],
    notaMedia: 4.4,
    totalAvaliacoes: 63,
  },
  {
    nome: 'Anel Prata Trançado',
    slug: 'anel-prata-tracado',
    descricao:
      'Aro trançado à mão em prata 925 maciça. Textura marcante com conforto de uso diário.',
    cuidados: CUIDADO_PRATA,
    preco: 149.9,
    material: 'PRATA_925',
    categoria: 'aneis',
    estoque: 16,
    pesoGramas: 4.2,
    tamanhos: ['14', '16', '18', '20', '22'],
    notaMedia: 4.7,
    totalAvaliacoes: 24,
  },
  {
    nome: 'Anel Sinete Oval',
    slug: 'anel-sinete-oval',
    descricao:
      'Sinete de face oval lisa, pronto para gravação de monograma. Peça de referência com pegada atemporal.',
    cuidados: CUIDADO_OURO,
    preco: 189.9,
    material: 'BANHADO_OURO',
    categoria: 'aneis',
    estoque: 13,
    pesoGramas: 6.8,
    tamanhos: ['16', '18', '20', '22'],
    lancamento: true,
    notaMedia: 4.7,
    totalAvaliacoes: 12,
  },
  {
    nome: 'Anel Duplo Vazado',
    slug: 'anel-duplo-vazado',
    descricao:
      'Dois aros paralelos unidos por elo vazado, criando efeito de sobreposição em uma peça só.',
    cuidados: CUIDADO_OURO,
    preco: 119.9,
    material: 'BANHADO_OURO',
    categoria: 'aneis',
    estoque: 8,
    pesoGramas: 2.3,
    tamanhos: ['14', '16', '18', '20'],
    lancamento: true,
    notaMedia: 4.5,
    totalAvaliacoes: 9,
  },

  // ─── Pulseiras ─────────────────────────────────────────────────────────────
  {
    nome: 'Pulseira Riviera Zircônias',
    slug: 'pulseira-riviera-zirconias',
    descricao:
      'Riviera cravejada em toda a extensão com zircônias em trilho. Brilho contínuo e fecho de segurança duplo.',
    cuidados: CUIDADO_OURO,
    preco: 219.9,
    precoPromocional: 179.9,
    material: 'BANHADO_OURO',
    categoria: 'pulseiras',
    estoque: 21,
    pesoGramas: 6.4,
    pedra: 'Zircônia',
    tamanhos: ['17cm', '19cm'],
    destaque: true,
    notaMedia: 4.8,
    totalAvaliacoes: 44,
  },
  {
    nome: 'Pulseira Elos Portuguesa',
    slug: 'pulseira-elos-portuguesa',
    descricao:
      'Elo português tradicional com acabamento diamantado. Estrutura robusta que mantém o formato com o tempo.',
    cuidados: CUIDADO_OURO,
    preco: 179.9,
    material: 'BANHADO_OURO',
    categoria: 'pulseiras',
    estoque: 26,
    pesoGramas: 8.1,
    tamanhos: ['18cm', '20cm'],
    notaMedia: 4.6,
    totalAvaliacoes: 30,
  },
  {
    nome: 'Pulseira Prata Veneziana Fina',
    slug: 'pulseira-prata-veneziana-fina',
    descricao:
      'Veneziana de 1mm em prata 925, delicada ao ponto de quase desaparecer no pulso. Ótima para mix com relógio.',
    cuidados: CUIDADO_PRATA,
    preco: 89.9,
    material: 'PRATA_925',
    categoria: 'pulseiras',
    estoque: 47,
    pesoGramas: 2.1,
    tamanhos: ['17cm', '19cm'],
    notaMedia: 4.7,
    totalAvaliacoes: 52,
  },
  {
    nome: 'Pulseira Prata Berloque Coração',
    slug: 'pulseira-prata-berloque-coracao',
    descricao:
      'Pulseira em prata 925 com berloque de coração liso. Aceita berloques adicionais para personalização.',
    cuidados: CUIDADO_PRATA,
    preco: 129.9,
    precoPromocional: 104.9,
    material: 'PRATA_925',
    categoria: 'pulseiras',
    estoque: 6,
    pesoGramas: 4.8,
    tamanhos: ['18cm'],
    notaMedia: 4.5,
    totalAvaliacoes: 35,
  },
  {
    nome: 'Bracelete Rígido Liso',
    slug: 'bracelete-rigido-liso',
    descricao:
      'Bracelete rígido de abertura lateral com acabamento espelhado. Encaixe firme e visual minimalista.',
    cuidados: CUIDADO_OURO,
    preco: 199.9,
    material: 'BANHADO_OURO',
    categoria: 'pulseiras',
    estoque: 14,
    pesoGramas: 14.2,
    tamanhos: ['Único'],
    lancamento: true,
    notaMedia: 4.6,
    totalAvaliacoes: 17,
  },
  {
    nome: 'Pulseira Prata Malha Grumet',
    slug: 'pulseira-prata-malha-grumet',
    descricao:
      'Malha grumet achatada em prata 925 maciça. Peso confortável e brilho que resiste ao uso diário.',
    cuidados: CUIDADO_PRATA,
    preco: 239.9,
    material: 'PRATA_925',
    categoria: 'pulseiras',
    estoque: 11,
    pesoGramas: 13.5,
    tamanhos: ['19cm', '21cm'],
    lancamento: true,
    notaMedia: 4.8,
    totalAvaliacoes: 13,
  },

  // ─── Conjuntos ─────────────────────────────────────────────────────────────
  {
    nome: 'Conjunto Ponto de Luz Colar e Brinco',
    slug: 'conjunto-ponto-de-luz-colar-brinco',
    descricao:
      'Colar ponto de luz e brincos combinando, ambos com zircônia lapidada. Chega em embalagem-presente pronta para entregar.',
    cuidados: CUIDADO_OURO,
    preco: 279.9,
    precoPromocional: 219.9,
    material: 'BANHADO_OURO',
    categoria: 'conjuntos',
    estoque: 22,
    pesoGramas: 6.1,
    pedra: 'Zircônia',
    destaque: true,
    notaMedia: 4.9,
    totalAvaliacoes: 58,
  },
  {
    nome: 'Conjunto Argolas Trio Sobreposição',
    slug: 'conjunto-argolas-trio-sobreposicao',
    descricao:
      'Trio de argolas em tamanhos escalonados (1,2cm, 2cm e 3cm) para compor múltiplos furos com harmonia.',
    cuidados: CUIDADO_OURO,
    preco: 199.9,
    material: 'BANHADO_OURO',
    categoria: 'conjuntos',
    estoque: 27,
    pesoGramas: 5.4,
    notaMedia: 4.7,
    totalAvaliacoes: 36,
  },
  {
    nome: 'Conjunto Prata Colar e Pulseira Veneziana',
    slug: 'conjunto-prata-colar-pulseira-veneziana',
    descricao:
      'Colar e pulseira em malha veneziana de prata 925, mesma espessura e acabamento. Coordenação sem esforço.',
    cuidados: CUIDADO_PRATA,
    preco: 289.9,
    precoPromocional: 239.9,
    material: 'PRATA_925',
    categoria: 'conjuntos',
    estoque: 15,
    pesoGramas: 9.8,
    notaMedia: 4.8,
    totalAvaliacoes: 26,
  },
  {
    nome: 'Conjunto Aliança e Aparador',
    slug: 'conjunto-alianca-aparador',
    descricao:
      'Solitário com aparador cravejado desenhados para encaixar perfeitamente. Vendidos juntos com desconto.',
    cuidados: CUIDADO_OURO,
    preco: 299.9,
    precoPromocional: 249.9,
    material: 'BANHADO_OURO',
    categoria: 'conjuntos',
    estoque: 9,
    pesoGramas: 4.5,
    pedra: 'Zircônia',
    tamanhos: ['14', '16', '18', '20'],
    notaMedia: 4.7,
    totalAvaliacoes: 21,
  },
  {
    nome: 'Conjunto Prata Brinco e Anel Estrela',
    slug: 'conjunto-prata-brinco-anel-estrela',
    descricao:
      'Brincos de estrela com anel de falange combinando, todos em prata 925. Conjunto leve para o dia a dia.',
    cuidados: CUIDADO_PRATA,
    preco: 149.9,
    material: 'PRATA_925',
    categoria: 'conjuntos',
    estoque: 4,
    pesoGramas: 2.4,
    tamanhos: ['Ajustável'],
    lancamento: true,
    notaMedia: 4.5,
    totalAvaliacoes: 11,
  },
  {
    nome: 'Conjunto Pérolas Colar Brinco e Pulseira',
    slug: 'conjunto-perolas-colar-brinco-pulseira',
    descricao:
      'Trio completo com pérolas de água doce montadas em banho de ouro 18k. Escolha tradicional para madrinhas e formaturas.',
    cuidados: CUIDADO_OURO,
    preco: 449.9,
    precoPromocional: 379.9,
    material: 'BANHADO_OURO',
    categoria: 'conjuntos',
    estoque: 7,
    pesoGramas: 16.3,
    pedra: 'Pérola de água doce',
    lancamento: true,
    notaMedia: 4.9,
    totalAvaliacoes: 18,
  },

  // ─── Piercings ─────────────────────────────────────────────────────────────
  {
    nome: 'Piercing Argolinha Clicker',
    slug: 'piercing-argolinha-clicker',
    descricao:
      'Argolinha de 8mm com fecho clicker, prática de colocar e retirar. Indicada para helix e lóbulo já cicatrizados.',
    cuidados: CUIDADO_OURO,
    preco: 69.9,
    precoPromocional: 55.9,
    material: 'BANHADO_OURO',
    categoria: 'piercings',
    estoque: 58,
    pesoGramas: 0.6,
    tamanhos: ['8mm', '10mm'],
    destaque: true,
    notaMedia: 4.7,
    totalAvaliacoes: 49,
  },
  {
    nome: 'Piercing Prata Ponto de Luz',
    slug: 'piercing-prata-ponto-de-luz',
    descricao:
      'Micro piercing de rosca interna em prata 925 com zircônia de 2mm. Discreto e confortável para uso contínuo.',
    cuidados: CUIDADO_PRATA,
    preco: 59.9,
    material: 'PRATA_925',
    categoria: 'piercings',
    estoque: 63,
    pesoGramas: 0.4,
    pedra: 'Zircônia',
    notaMedia: 4.8,
    totalAvaliacoes: 71,
  },
  {
    nome: 'Piercing Fake Argola Espiral',
    slug: 'piercing-fake-argola-espiral',
    descricao:
      'Piercing fake de encaixe em espiral, sem necessidade de furo. Firme o suficiente para o dia inteiro.',
    cuidados: CUIDADO_OURO,
    preco: 44.9,
    material: 'BANHADO_OURO',
    categoria: 'piercings',
    estoque: 82,
    pesoGramas: 0.5,
    notaMedia: 4.3,
    totalAvaliacoes: 38,
  },
  {
    nome: 'Piercing Prata Barbell Reto',
    slug: 'piercing-prata-barbell-reto',
    descricao:
      'Barbell reto em prata 925 com esferas rosqueáveis. Versátil para helix, tragus e industrial.',
    cuidados: CUIDADO_PRATA,
    preco: 49.9,
    material: 'PRATA_925',
    categoria: 'piercings',
    estoque: 3,
    pesoGramas: 0.5,
    tamanhos: ['6mm', '8mm', '10mm'],
    notaMedia: 4.6,
    totalAvaliacoes: 29,
  },
  {
    nome: 'Piercing Corrente Dupla Helix',
    slug: 'piercing-corrente-dupla-helix',
    descricao:
      'Piercing com corrente dupla conectando helix e lóbulo. Peça de destaque para quem já tem múltiplos furos.',
    cuidados: CUIDADO_OURO,
    preco: 109.9,
    material: 'BANHADO_OURO',
    categoria: 'piercings',
    estoque: 17,
    pesoGramas: 1.1,
    lancamento: true,
    notaMedia: 4.5,
    totalAvaliacoes: 15,
  },
  {
    nome: 'Piercing Prata Nostril Curvo',
    slug: 'piercing-prata-nostril-curvo',
    descricao:
      'Nostril em prata 925 com haste curva que trava naturalmente na narina. Pedra de zircônia de 1,5mm.',
    cuidados: CUIDADO_PRATA,
    preco: 39.9,
    precoPromocional: 31.9,
    material: 'PRATA_925',
    categoria: 'piercings',
    estoque: 44,
    pesoGramas: 0.3,
    pedra: 'Zircônia',
    lancamento: true,
    notaMedia: 4.4,
    totalAvaliacoes: 23,
  },
];
